all:
	g++ ./source/automataNeuman.cpp ./source/main.cpp ./source/plotting.cpp -o simula
run:
	g++ ./source/automataNeuman.cpp ./source/main.cpp ./source/plotting.cpp -o simula
	./simula
clear:
	find . -type f -executable -exec rm '{}' \;

#   mingw32-make -f Makefile #Para funcionar no Windows, Linux será somente escrever no terminal "make", ou "make run", acho